function paths = getpaths()

paths = {...
    '/', ...
    '/GuiMain', ...
    '/GuiMain/AxesData', ...
    '/GuiMain/AxesSDG', ...
    '/CurrElem', ...
    '/Group', ...
    '/Group/ProcStream', ...
    '/Group/ProcStream/Funcs', ...
    '/NirsFiles', ...
    '/ProcStream', ...
    '/ProcStream/Funcs', ...
    '/Run', ...
    '/Run/ProcStream', ...
    '/Run/ProcStream/Funcs', ...
    '/Subj', ...
    '/Subj/ProcStream', ...
    '/Subj/ProcStream/Funcs', ...
    '/Utils', ...
    '/stimGUI', ...
    };
