function paths = getpaths()

paths = {...
    '/'; ...
    '/GuiMain'; ...
    '/GuiMain/AxesData'; ...
    '/GuiMain/AxesSDG'; ...
    '/CurrElem'; ...
    '/Group'; ...
    '/Group/ProcStream'; ...
    '/Group/ProcStream/Funcs'; ...
    '/NirsFiles'; ...
    '/PlotProbe'; ...
    '/ProcStream'; ...
    '/ProcStream/Funcs'; ...
    '/Run'; ...
    '/Run/ProcStream'; ...
    '/Run/ProcStream/Funcs'; ...
    '/Snirf'; ...
    '/Snirf/Hdf5'; ...
    '/Snirf/Examples'; ...
    '/Subj'; ...
    '/Subj/ProcStream'; ...
    '/Subj/ProcStream/Funcs'; ...
    '/Utils'; ...
    '/stimGUI'; ...
    };

% Remove excluded paths from other applications
while 1
    paths_excl = exclpaths({'Homer3.m','Homer2_UI.m'}, './utils');
    if isempty(paths_excl)
        break;
    end
    
    paths_excl_str = '';
    for ii=1:length(paths_excl)
        fprintf('Removing excluded path %s\n', paths_excl{ii});
        if isempty(paths_excl_str)
            paths_excl_str = paths_excl{ii};
        else
            paths_excl_str = [paths_excl_str, ';', paths_excl{ii}];
        end
    end
    rmpath(paths_excl_str);
end

