function foos = initErrFlagsStruct(n)

foos = struct('FileCorrupt',0,...
              'SD',0,...
              'SD_Lambda',0,...
              'SD_SrcPos',0,...
              'SD_nSrcs',0,...
              'SD_DetPos',0,...
              'SD_nDets',0,...
              'SD_MeasList',0,...
              'SD_auxChannels',0,...
              'SD_SpatialUnit',0,...
              'd',0,...
              't',0,...
              's',0,...
              'aux',0,...
              'ml',0,...
              'procInput',0,...
              'procInput_procFunc',0,...
              'procInput_procParam',0,...
              'procInput_changeFlag',0,...
              'procInput_SD',0,...
              'CondNames',0,...
              'status',0,...
              'subj',0);

foos = repmat(foos,n,1);
