function axesData = InitAxesData(handles, group, currElem)

axesSDG = InitAxesSDG(handles);
axesData = struct(...
                     'handles', struct(...
                                       'axes', handles.axesData, ...
                                       'radiobuttonPlotConc', handles.radiobuttonPlotConc, ...
                                       'radiobuttonPlotOD', handles.radiobuttonPlotOD, ...
                                       'radiobuttonPlotRaw', handles.radiobuttonPlotRaw, ...
                                       'checkboxPlotHRF', handles.checkboxPlotHRF, ...
                                       'listboxPlotWavelength', handles.listboxPlotWavelength, ...
                                       'listboxPlotConc', handles.listboxPlotConc, ...
                                       'popupmenuConditions', handles.popupmenuConditions, ...
                                       'menuItemViewHRFStdErr', handles.menuItemViewHRFStdErr ...
                                      ), ...
                     'datatype', 0, ...
                     'condition', 0, ...
                     'ch', 0, ...
                     'wl', 0, ...
                     'hbType', 0, ...
                     'linecolor', axesSDG.linecolor, ...
                     'linestyle', {{'-','--',':'}}, ...
                     'guisetting', struct(...
                                          'RAW',1, ...
                                          'RAW_HRF',2, ...
                                          'OD',3, ...
                                          'OD_HRF',4, ...
                                          'CONC',5, ...
                                          'CONC_HRF',6 ...
                                         ), ...
                     'sclConc', 1e6, ...                      % convert Conc from Molar to uMolar
                     'axesSDG', axesSDG, ...
                     'showStdErr', false ... 
                 );

axesData = UpdateAxesDataCondition(axesData, group, currElem);
setWl(axesData, currElem.procElem.SD.Lambda);

axesData.datatype  = getDatatype(axesData);
axesData.condition = getCondition(axesData);
axesData.wl        = getWl(axesData, currElem.procElem.SD.Lambda);
axesData.hbType    = getHbType(axesData);
axesData.ch        = GetAxesSDGSelection(axesData.axesSDG);
if strcmp(get(handles.menuItemViewHRFStdErr, 'checked'), 'on');
    axesData.showStdErr = true;
elseif strcmp(get(handles.menuItemViewHRFStdErr, 'checked'), 'off');
    axesData.showStdErr = false;
end

if axesData.datatype == axesData.guisetting.RAW | ...
   axesData.datatype == axesData.guisetting.RAW_HRF

    set(axesData.handles.listboxPlotWavelength, 'visible','on');
    set(axesData.handles.listboxPlotConc, 'visible','off');
    
elseif axesData.datatype == axesData.guisetting.OD | ...
       axesData.datatype == axesData.guisetting.OD_HRF
    
    set(axesData.handles.listboxPlotWavelength, 'visible','on');
    set(axesData.handles.listboxPlotConc, 'visible','off');
    
elseif axesData.datatype == axesData.guisetting.CONC | ...
       axesData.datatype == axesData.guisetting.CONC_HRF
    
    set(axesData.handles.listboxPlotWavelength, 'visible','off');
    set(axesData.handles.listboxPlotConc, 'visible','on');
    
end
