function guiMain = InitGuiMain(handles, dataTree)

axesSDG = InitAxesSDG(handles);
axesData = InitAxesData(handles, axesSDG);
guiMain = struct(...
                     'name', 'guiMain', ...
                     'handles', struct(...
                                       'radiobuttonPlotConc', handles.radiobuttonPlotConc, ...
                                       'radiobuttonPlotOD', handles.radiobuttonPlotOD, ...
                                       'radiobuttonPlotRaw', handles.radiobuttonPlotRaw, ...
                                       'checkboxPlotHRF', handles.checkboxPlotHRF, ...
                                       'checkboxPlotProbe', handles.checkboxPlotProbe, ...
                                       'listboxPlotWavelength', handles.listboxPlotWavelength, ...
                                       'listboxPlotConc', handles.listboxPlotConc, ...
                                       'popupmenuConditions', handles.popupmenuConditions, ...
                                       'menuItemViewHRFStdErr', handles.menuItemViewHRFStdErr ...
                                      ), ...
                     'datatype', 0, ...
                     'condition', 0, ...
                     'ch', 0, ...
                     'wl', 0, ...
                     'hbType', 0, ...
                     'buttonVals', struct(...
                                          'RAW',1, ...
                                          'RAW_HRF',2, ...
                                          'OD',4, ...
                                          'OD_HRF',8, ...
                                          'CONC',16, ...
                                          'CONC_HRF',32 ...
                                         ), ...
                     'sclConc', 1e6, ...                      % convert Conc from Molar to uMolar
                     'axesSDG', axesSDG, ...
                     'axesData', axesData, ...
                     'showStdErr', false, ... 
                     'flagPlotRange', 0, ...
                     'applyEditCurrNodeOnly', true ...
                 );

guiMain = UpdateAxesDataCondition(guiMain, dataTree);
setWl(guiMain, dataTree.currElem.procElem.GetWls());

guiMain.datatype  = getDatatype(guiMain);
guiMain.condition = getCondition(guiMain);
guiMain.wl        = getWl(guiMain, dataTree.currElem.procElem.GetWls());
guiMain.hbType    = getHbType(guiMain);
guiMain.ch        = axesSDG.iCh;

if strcmp(get(handles.menuItemViewHRFStdErr, 'checked'), 'on');
    guiMain.showStdErr = true;
elseif strcmp(get(handles.menuItemViewHRFStdErr, 'checked'), 'off');
    guiMain.showStdErr = false;
end

if guiMain.datatype == guiMain.buttonVals.RAW || guiMain.datatype == guiMain.buttonVals.RAW_HRF

    set(guiMain.handles.listboxPlotWavelength, 'visible','on');
    set(guiMain.handles.listboxPlotConc, 'visible','off');
    
elseif guiMain.datatype == guiMain.buttonVals.OD || guiMain.datatype == guiMain.buttonVals.OD_HRF
    
    set(guiMain.handles.listboxPlotWavelength, 'visible','on');
    set(guiMain.handles.listboxPlotConc, 'visible','off');
    
elseif guiMain.datatype == guiMain.buttonVals.CONC || guiMain.datatype == guiMain.buttonVals.CONC_HRF
    
    set(guiMain.handles.listboxPlotWavelength, 'visible','off');
    set(guiMain.handles.listboxPlotConc, 'visible','on');
    
end


if get(handles.checkboxApplyProcStreamEditToAll, 'value')
    guiMain.applyEditCurrNodeOnly = false;
else
    guiMain.applyEditCurrNodeOnly = true;
end

