function procResult = InitProcResult()

procResult = struct(...
                    'dod',[],...
                    'dc',[],...
                    'dodAvg',[],...
                    'dcAvg',[],...
                    'dodAvgStd',[],...
                    'dcAvgStd',[],...
                    'dodSum2',[],...
                    'dcSum2',[],...
                    'tHRF',[],...
                    'nTrials',[],...
                    'SD',[]...
                   );
