
% When ever you change this function, then it is necessary to run
% procStreamGenHelp() from the matlab command line

function reg = procStreamRegRun()

reg = {
'@ hmrR_Intensity2OD dod (d'; ...
'@ hmrR_PruneChannels SD (d,SD,tIncMan dRange %.0e_%.0e 0_1e7 SNRthresh %d 2 reset %d 0'; ...
'@ hmrR_MotionArtifact tIncAuto (dod,t,SD,tIncMan tMotion %0.1f 0.5 tMask %0.1f 1 STDEVthresh %0.1f 50 AMPthresh %0.2f 5'; ...
'@ hmrR_MotionArtifactByChannel [tIncAuto,tIncChAuto] (dod,t,SD,tIncMan tMotion %0.1f 0.5 tMask %0.1f 1 STDEVthresh %0.1f 50 AMPthresh %0.2f 5'; ...
'@ hmrR_StimRejection [s,tRangeStimReject] (t,s,tIncAuto,tIncMan tRange %0.1f_%0.1f -5_10'; ...
'@ hmrR_BandpassFilt dod (dod,t hpf %0.3f 0 lpf %0.2f 3'; ...
'@ hmrR_OD2Conc dc (dod,SD ppf %0.1f_%0.1f 6_6'; ...
'@ hmrR_PCAFilter #[dc,svs,nSV] (dc,SD,tIncMan nSV %0.1f_%0.1f 0_0'; ...
'@ hmrR_BlockAvg [dcAvg,dcAvgStd,tHRF,nTrials,dcSum2] (dc,s,t trange %0.1f_%0.1f -2_20'; ...
'@ hmrR_DeconvHRF_DriftSS [dcAvg,dcAvgStd,tHRF,nTrials,dc,dcResid,dcSum2,beta,R] (dc,s,t,SD,aux,tIncAuto trange %0.1f_%0.1f -2.0_20.0 glmSolveMethod %d 1 idxBasis %d 1 paramsBasis %0.1f_%0.1f_%0.1f_%0.1f_%0.1f_%0.1f 1.0_1.0 rhoSD_ssThresh %0.1f 0.0 flagSSmethod %d 1 driftOrder %d 0 flagMotionCorrect %d 0'; ...
};
