function procInput = procStreamCopy2Old(procInput)

if procInput.conversionFlag==false
    return;
end

msg{1} = sprintf('NIRS files were generated by Homer2. About to save processing stream\n');
msg{2} = sprintf('to NIRS files. Do you want to keep older file format (so that this subject\n');
msg{3} = sprintf('folder is still loadable in homer2) or save in newer format?\n'); 
fprintf([msg{:}]);

% q = menu([msg{:}], 'Save in Current Format', 'Save in Older Format');
% if q==1
%     procInput.conversionFlag = 0;
%     return;
% end

procFunc = procInput.procFunc;
procFunc2 = struc([]);

nFunc = 0;
for ii=1:length(procFunc)
    nFunc=nFunc+1;
    procFunc2.funcName{ii}        = procFunc(ii).funcName;
    procFunc2.funcNameUI{ii}      = procFunc(ii).funcNameUI;
    procFunc2.funcArgOut{ii}      = procFunc(ii).funcArgOut;
    procFunc2.funcArgIn{ii}       = procFunc(ii).funcArgIn;
    procFunc2.nFuncParam(ii)      = procFunc(ii).nFuncParam;
    procFunc2.nFuncParamVar(ii)   = procFunc(ii).nFuncParamVar;
    procFunc2.funcParam{ii}       = procFunc(ii).funcParam;
    procFunc2.funcParamFormat{ii} = procFunc(ii).funcParamFormat;
    procFunc2.funcParamVal{ii}    = procFunc(ii).funcParamVal;
end

procInput.procFunc = procFunc2;

