function procInput = procStreamCopy2Old(procInput)

if procInput.conversionFlag==false
    return;
end

msg{1} = sprintf('NIRS files were generated by Homer2. About to save processing stream\n');
msg{2} = sprintf('to NIRS files. Do you want to keep older file format (so that this subject\n');
msg{3} = sprintf('folder is still loadable in homer2) or save in newer format?\n'); 
fprintf([msg{:}]);

% q = menu([msg{:}], 'Save in Current Format', 'Save in Older Format');
% if q==1
%     procInput.conversionFlag = 0;
%     return;
% end

func = procInput.func;
procFunc = struc([]);

nFunc = 0;
for ii=1:length(func)
    nFunc=nFunc+1;
    procFunc.funcName{ii}        = func(ii).funcName;
    procFunc.funcNameUI{ii}      = func(ii).funcNameUI;
    procFunc.funcArgOut{ii}      = func(ii).funcArgOut;
    procFunc.funcArgIn{ii}       = func(ii).funcArgIn;
    procFunc.nFuncParam(ii)      = func(ii).nFuncParam;
    procFunc.nFuncParamVar(ii)   = func(ii).nFuncParamVar;
    procFunc.funcParam{ii}       = func(ii).funcParam;
    procFunc.funcParamFormat{ii} = func(ii).funcParamFormat;
    procFunc.funcParamVal{ii}    = func(ii).funcParamVal;
end

procInput.procFunc = procFunc;

