function [contents, str] = procStreamDefaultFileRun()

contents = {...
    '%% run\n', ...
    '@ hmrR_Intensity2OD dod (d\n', ...
    '@ hmrR_MotionArtifact tIncAuto (dod,t,SD,tIncMan tMotion %%0.1f 0.5 tMask %%0.1f 1 STDEVthresh %%0.1f 50 AMPthresh %%0.1f 5\n', ...
    '@ hmrR_BandpassFilt dod (dod,t hpf %%0.3f 0.01 lpf %%0.1f 0.5\n', ...
    '@ hmrR_OD2Conc dc (dod,SD ppf %%0.1f_%%0.1f 6_6\n', ...
    '@ hmrR_StimRejection [s,tRangeStimReject] (t,s,tIncAuto,tIncMan tRange %%0.1f_%%0.1f -5_10\n', ...
    '@ hmrR_BlockAvg [dcAvg,dcAvgStd,tHRF,nTrials,dcSum2,dcTrials] (dc,s,t trange %%0.1f_%%0.1f -2_20\n' ...
    '\n\n', ...
    };

str = cell2str(contents);