function procResult = InitProcResultGroup()

procResult = struct(...
                    'dodAvg',[], ...
                    'dcAvg',[], ...
                    'dodAvgStd',[], ...
                    'dcAvgStd',[], ...
                    'tHRF',[], ...
                    'nTrials',[], ...
                    'tInc',[], ...
                    'SD',[], ...
                    'grpAvgPass',[] ...
                   );
