function procInput = InitProcInputGroup()

procInput = struct(...
                   'procParam',struct([]), ...
                   'procFunc',struct([]), ...
                   'changeFlag',0 ...
                   );
