function axesSDG = InitAxesSDG(handles)

p = [getAppDir(), 'SDGcolors.csv'];
rgb01 = csvread(p) / 255;
fprintf(['Loaded ', num2str(size(rgb01, 1)), ' colors from SDGcolors.csv.\n' ])

axesSDG = struct(...
                 'handles', struct(...
                                   'axes', handles.axesSDG, ...
                                   'SD', [], ...
                                   'ch', [] ...
                                  ), ...
                 'iCh', [], ...
                 'iSrcDet', [], ...
                 'linecolor', rgb01...
               );

