function axesData = InitAxesData(handles, axesSDG)

axesData = struct(...
                     'handles', struct(...
                                       'axes', handles.axesData ...
                                      ), ...
                     'SDPairColors', axesSDG.SDPairColors, ...
                     'linestyle', {{'-','--',':'}} ...
                 );

