function currElem = InitCurrElem(handles, funcptr)

currElem = struct(...    
    'handles', struct(...
        'listboxFiles',[], ...
        'listboxFilesErr',[], ...
        'textStatus',[], ...
        'radiobuttonProcTypeGroup',[], ...
        'radiobuttonProcTypeSubj',[], ...
        'radiobuttonProcTypeRun',[], ...
        'ProcStreamOptionsGUI',[] ...
    ), ...
    'funcPtrListboxFiles', [], ...
    'iFile',0, ...
    'iSubj',0, ...
    'iRun',0, ...
    'procType',0, ...
    'procElem', struct([]) ...
);

if exist('handles','var')

    currElem.handles.listboxFiles = handles.listboxFiles;
    set(currElem.handles.listboxFiles,'enable','off');
    currElem.iFile = get(currElem.handles.listboxFiles,'value');
    
    currElem.handles.listboxFilesErr = handles.listboxFilesErr;
    set(currElem.handles.listboxFilesErr,'enable','off');

    currElem.handles.textStatus = handles.textStatus;
    set(currElem.handles.textStatus,'enable','off');
    
    currElem.handles.radiobuttonProcTypeGroup = handles.radiobuttonProcTypeGroup;
    set(currElem.handles.radiobuttonProcTypeGroup,'enable','off');

    currElem.handles.radiobuttonProcTypeSubj = handles.radiobuttonProcTypeSubj;
    set(currElem.handles.radiobuttonProcTypeSubj,'enable','off');

    currElem.handles.radiobuttonProcTypeRun = handles.radiobuttonProcTypeRun;
    set(currElem.handles.radiobuttonProcTypeRun,'enable','off');
    
    currElem = getProcType(currElem);

end

if exist('funcptr','var')
   currElem.funcPtrListboxFiles = funcptr;
end

