function procResult = InitProcResultSubj()

procResult = struct(...
                    'dodAvg',[], ...
                    'dcAvg',[], ...
                    'dodAvgStd',[], ...
                    'dcAvgStd',[], ...
                    'tHRF',[], ...
                    'nTrials',[], ...
                    'SD',[] ...
                   );


