function procInput = InitProcInputSubj()

procInput = struct(...
                   'procParam',struct([]), ...
                   'procFunc',struct([]), ...
                   'changeFlag',0, ...
                   'conversionFlag',0 ...
                   );


