function subj = createSubj(fname, iSubj, iRun, rnum)

subj = [];

[sname rnum_tmp iExt] = getSubjNameAndRun(fname, rnum);
run = createRun(fname, iSubj, iRun, rnum);
subj0 = struct(...
               'name', sname, ...
               'type', 'subj', ...
               'iSubj', iSubj, ...
               'SD', struct([]), ...
               'CondNames',{{}}, ...
               'CondSubj2Run',[], ...
               'CondSubj2Group',[], ...
               'procInput', InitProcInputSubj(), ...
               'procResult', InitProcResultSubj(), ...         
               'runs', run ...
              );

if isempty(sname)
    subj = repmat(subj0,0,0);
else
    subj = subj0;
end

